install apple-gcc42
install aspell
install brew-cask
install colordiff
install ctags
install curl-ca-bundle
install dos2unix
install drip
install elixir
install emacs
install erlang
install gcc49
install git
install git-extras
install gnu-sed
install gnutls
install go
install grep
install gtk+
install htop-osx
install imagemagick
install intltool
install leiningen
install libksba
install libyaml
install macvim
install mercurial
install mobile-shell
install mongodb
install mysql
install nginx
install nmap
install node
install openssl098
install phantomjs
install postgresql92
install py2cairo
install pygobject
install qt
install rabbitmq
install rbenv-binstubs
install reattach-to-user-namespace
install redis
install rethinkdb
install riak
install sqlite
install ssh-copy-id
install tcpdump
install the_silver_searcher
install tmux
install tree
install watch
install wdiff
install wget
install zsh
