TAPS = %w[
  zph/zph
  cirruslabs/cli
  earthly/earthly
  espanso/espanso
  homebrew/bundle
  homebrew/cask
  homebrew/cask-fonts
  homebrew/core
  homebrew/services
  microsoft/git
  neovim/neovim
  rcmdnk/file
]

BREWS = %w[
  antigen
  asdf
  aspell
  python@3.10
  awscli
  bash
  bat
  cabal-install
  pkg-config
  cask
  chamber
  cmake
  colordiff
  ctags
  zstd
  dhall
  dhall-json
  diff-so-fancy
  direnv
  dos2unix
  esbuild
  fasd
  ffind
  fish
  fzf
  gh
  git
  git-extras
  gnupg
  go
  goreleaser
  hadolint
  htop
  httpie
  hub
  hugo
  jpeg
  jq
  just
  ldns
  libfido2
  libssh
  libxml2
  mas
  mosh
  neovim
  openssh
  openssl@3
  pwgen
  reattach-to-user-namespace
  ripgrep
  rlwrap
  rsync
  shellcheck
  shfmt
  ssh-copy-id
  starship
  stow
  terraform
  tmux
  watch
  watchexec
  wdiff
  wget
  yarn
  zoxide
  zsh
  cirruslabs/cli/tart
  earthly/earthly/earthly
  go-swagger/go-swagger/go-swagger
]

CASKS = %w[
  zph/zph/datagrip
  zph/zph/dash
  alfred
  dash
  1password
  1password-cli
  alacritty
  aws-vault
  bartender
  ccmenu
  fantastical
  font-fira-code
  git-credential-manager-core
  rectangle
  the-unarchiver
  vlc
  espanso
  keybase
  telegram
  karabiner-elements
  raindropio
  visual-studio-code
]

MAS = [
  ["1Password for Safari", 1569813296],
  ["GrandPerspective", 1111570163],
  ["iA Writer", 775737590],
  ["Keynote", 409183694],
  ["Kindle", 405399194],
  ["Numbers", 409203825],
  ["Pages", 409201541],
  ["Pixelmator", 407963104],
  ["rcmd", 1596283165],
  ["Slack", 803453959],
  ["YubiKey Personalization Tool", 638161122],
]

TAPS.each { |c| tap c }
CASKS.each { |c| cask c }
BREWS.each { |c| brew c }
brew "sqlite", link: true
brew "curl", link: true
MAS.each {|c| mas c.first, id: c[1] }
