# export GOROOT=/usr/local/go
# export GOROOT=/usr/local/Cellar/go/1.2.1
# export GOPATH=$HOME/tmp/go
# export GOBIN=$GOROOT/bin
# export PATH=$PATH:$GOBIN
# export PATH=$PATH:$GOPATH/bin
# export GOROOT=/usr/local/Cellar/go/1.2.1/
export GOPATH=$HOME/src/golang
# export PATH=$PATH:/usr/local/Cellar/go/1.2.1/libexec/bin
# export PATH=$PATH:$GOROOT/bin
