#!/usr/bin/env bash

set -eou pipefail

EXCLUSIONS=(
  ~/.antigen
  ~/.cache
  ~/.gem
  ~/.glide
  ~/.m2
  ~/.npm
  ~/.pyenv
  ~/.rubies
  ~/.tldrc
  ~/.tmux
  ~/.vscode
  ~/Documents
  ~/Dropbox
  ~/Library/Caches
  ~/Library/Containers/com.docker.docker/Data/vms
  ~/Library/Logs
  ~/src
  ~/tmp
  ~/"VirtualBox VMs"
)

for path in "${EXCLUSIONS[@]}";do
  # remove then add provides a simple
  # way to avoid adding duplicate exclusions
  # which is default behavior if an exclusion is already in list.
  tmutil removeexclusion -p "$path"
  echo "--> Adding tmutils exclusion for $path"
  tmutil addexclusion -p "$path"
done
